services:
  watcharr:
    # The :latest tag is used for simplicity, it is recommended
    # to use an actual version, then when updating check the releases for changelogs.
    image: ghcr.io/sbondco/watcharr:latest
    container_name: watcharr
    ports:
      - 3080:3080
    volumes:
      # Contains all of watcharr data (database & cache)
      - /mnt/dockpool/beluga/Watcharr/container_data:/data
    restart: unless-stopped

    labels:
      - "net.unraid.docker.icon=https://i.imgur.com/5Ah733A.png"
      - "net.unraid.docker.webui=https://watcharr.cubetto.local/"
